---
title: "Niche webscraping part"
author: "Augustus Ge"
date: "November 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
get_names=function(a){
  names=vector(length=0,mode="character")
  for(i in 1:a){
    url=str_c("https://www.niche.com/colleges/search/best-colleges/?page=",i)
     webpages <- read_html(url)
     name_data <- html_text(html_nodes(webpages, ".search-result__title" ))  
     as.vector(name_data)
     names=c(names,as.vector(name_data))
  }
  names=str_replace_all(names," ","-")
  names
}
get_names(4)

```

```{r}

get_data <- function(name){
  url1 <-"https://www.niche.com/colleges"
  url2 <- str_c(url1,"/",name,"/")
  webpages <- read_html(url2)
  
  name_data <- html_text(html_nodes(webpages, ".postcard__title" ))  
  ACT_data <- html_text(html_nodes(webpages, "#admissions .scalar--three:nth-child(2) .scalar__value span" ))
  SAT_data <- html_text(html_nodes(webpages, css = "#admissions > div.profile__buckets > div.profile__bucket--3 > div > div > div:nth-child(1) > div.scalar__value > span"))
  app_fee <- html_text(html_nodes(webpages, css = "#admissions > div.profile__buckets > div.profile__bucket--3 > div > div > div:nth-child(3) > div.scalar__value > span"))
  ACT_SAT_req <- html_text(html_nodes(webpages, css = "#admissions > div.profile__buckets > div.profile__bucket--3 > div > div > div:nth-child(4) > div.scalar__value > span"))
  ed_ea <- html_text(html_nodes(webpages, css = "#admissions > div.profile__buckets > div.profile__bucket--3 > div > div > div:nth-child(6) > div.scalar__value > span"))
  app_deadline <- html_text(html_nodes(webpages, css = "#admissions > div.profile__buckets > div.profile__bucket--2 > div > div > div > div.scalar__value > span"))
  undergrad_pop <- html_text(html_nodes(webpages, css = "#students > div.profile__buckets > div.profile__bucket--1 > div > div > div.scalar > div.scalar__value > span:nth-child(1)"))
  acceptance_data <- html_text(html_nodes(webpages, "#admissions .profile__bucket--1 .scalar__value span" ))
  annualtuition_data <- html_text(html_nodes(webpages, "#cost .scalar__value span:nth-child(1)" ))
  link_data <-  html_text(html_nodes(webpages, ".profile__website__link" ))
  SFRatio_data <- html_text(html_nodes(webpages, ".profile-grade+ .scalar--three .scalar__value span" ))
  Eve_data <- html_text(html_nodes(webpages, "#academics .scalar--three+ .scalar--three .scalar__value span" ))
  url_review <- str_c(url2,"/reviews/")
  webpage2<- read_html(url_review)
  review_data <- html_text(html_nodes(webpage2, ".overflow-text__content div" ))
  
  print(name_data)
  print(ACT_data)
  print(SAT_data)
  print(app_fee)
  print(ACT_SAT_req)
  print(ed_ea)
  print(undergrad_pop)
  print(app_deadline)
  print(undergrad_pop) 
  print(acceptance_data)
  print(annualtuition_data)
  print(link_data)
  print(SFRatio_data)
  print(Eve_data)
  print(review_data)
}

  
  
  
  


```

```{r}
get_data("Brown-University") 



```




