---
title: "Scraping_Airline_Data_Outline"
author: "Augustus Ge"
date: "November 7, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
library(rvest)
library(stringr)
library(xml2)
```


```{r}
# Run second
get_names=function(a){
  names=vector(length=0,mode="character")
  for(i in 1:a){
    url=str_c("https://www.niche.com/colleges/search/best-colleges/?page=",i)
     webpages <- read_html(url)
     name_data <- html_text(html_nodes(webpages, ".search-result__title" ))  
     name_data <- as.vector(name_data)
     names=c(names, name_data)
  }
  names=str_replace_all(names," ","-")
  names=str_replace_all(names, "&", "-and-")
  return(names)
}
get_names(4)

```

```{r}
# Run Third
get_real_names=function(a){
  names=vector(length=0,mode="character")
  for(i in 1:a){
    url=str_c("https://www.niche.com/colleges/search/best-colleges/?page=",i)
     webpages <- read_html(url)
     name_data <- html_text(html_nodes(webpages, ".search-result__title" ))  
     name_data <- as.vector(name_data)
     names=c(names, name_data)
  }
  return(names)
}
```



```{r}
# Run First

get_data <- function(name){
  url1 <-"https://www.niche.com/colleges"
  url2 <- str_c(url1,"/",name,"/")
  webpages <- read_html(url2)
  name_data <- html_text(html_nodes(webpages, ".postcard__title" ))  
  ACT_data <- html_text(html_nodes(webpages, "#admissions .scalar--three:nth-child(2) .scalar__value span" ))
  if(length(ACT_data) == 0) ACT_data <- NA
  SAT_data <- html_text(html_nodes(webpages, css = "#admissions > div.profile__buckets > div.profile__bucket--3 > div > div > div:nth-child(1) > div.scalar__value > span"))
  if(length(SAT_data) == 0) SAT_data <- NA
  app_fee <- html_text(html_nodes(webpages, css = "#admissions > div.profile__buckets > div.profile__bucket--3 > div > div > div:nth-child(3) > div.scalar__value > span"))
  if(length(app_fee) == 0) app_fee <- NA
  ed_ea <- html_text(html_nodes(webpages, css = "#admissions > div.profile__buckets > div.profile__bucket--3 > div > div > div:nth-child(6) > div.scalar__value > span"))
  if(length(ed_ea) == 0) ed_ea <- NA
  app_deadline <- html_text(html_nodes(webpages, css = "#admissions > div.profile__buckets > div.profile__bucket--2 > div > div > div > div.scalar__value > span"))
  if(length(app_deadline) == 0) app_deadline <- NA
  undergrad_pop <- html_text(html_nodes(webpages, css = "#students > div.profile__buckets > div.profile__bucket--1 > div > div > div.scalar > div.scalar__value > span:nth-child(1)"))
  if(length(undergrad_pop) == 0) undergrad_pop <- NA
    acceptance_data <- html_text(html_nodes(webpages, "#admissions .profile__bucket--1 .scalar__value span" ))
    if(length(acceptance_data) == 0) acceptance_data <- NA
  annualtuition_data <- html_text(html_nodes(webpages, "#cost .scalar__value span:nth-child(1)" ))
    if(length(annualtuition_data) == 0) annualtuition_data <- NA
  link_data <-  html_text(html_nodes(webpages, ".profile__website__link" ))
    if(length(link_data) == 0) link_data <- NA
  SFRatio_data <- html_text(html_nodes(webpages, ".profile-grade+ .scalar--three .scalar__value span" ))
    if(length(SFRatio_data) == 0) SFRatio_data <- NA
  Eve_data <- html_text(html_nodes(webpages, "#academics .scalar--three+ .scalar--three .scalar__value span" ))
  
  url_review <- str_c(url2,"/reviews/")
  webpage2<- read_html(url_review)
  review_data <- html_text(html_nodes(webpage2, ".overflow-text__content div" ))
  
  url_review <- str_c(url2,"/reviews/")
  webpage2<- read_html(url_review)
  review_data <- html_text(html_nodes(webpage2, ".overflow-text__content div" ))
  # print(name_data)
  # print(ACT_data)
  # print(SAT_data)
  # print(ACT_SAT_req)
  # print(ed_ea)
  # print(app_fee)
  # print(app_deadline)
  # print(undergrad_pop)
  # print(acceptance_data)
  # print(annualtuition_data)
  # print(link_data)
  # print(SFRatio_data)
  # print(Eve_data)
  # print(review_data)
  
  return(c(name_data, ACT_data, SAT_data, ed_ea, app_fee, app_deadline, undergrad_pop, acceptance_data, annualtuition_data, link_data[1], SFRatio_data, Eve_data))
}

```

```{r}
get_data("harvard-university") 

```



```{r}
# Run Fourth
# Initialize data frame
df <- data.frame(matrix(nrow = 100, ncol = 12))
# name_data, ACT_data, SAT_data, ACT_SAT_req, ed_ea, app_fee, app_deadline, undergrad_pop, acceptance_data, annualtuition_data, link_data[1], SFRatio_data, Eve_data
colnames(df) <- c("School", "ACT Middle 50%", "SAT Middle 50%",	"ED/EA", "Application Fee", "Application Deadline", "Undergraduate Population", "Acceptance Rate", "Annual Tuition", "Application Website", "Student:Faculty Ratio", "Evening Degree Programs")

for(i in 1:100){
  df[i,] <- (get_data(get_names(4)[i]))
}
 
# Name the schools properly. Initial data frame creation has unwanted some strings
df$School <- get_real_names(4)
```


```{r}
# Run Fifth
# Switch app_deadline and acceptance_data in these rows
# For some reason on these schools the 7th and the 9th variable have swapped css
seq_vec <- c(11, 15, 17, 18, 33, 35, 43, 50, 58, 66, 82, 83, 85, 87, 97, 100)
temp <- df[seq_vec, 6]
df[seq_vec, 6] <- df[seq_vec, 8]
df[seq_vec, 8] <- temp

  
```


```{r}
# Add columns of Min & Max ACT and SAT
library(dplyr)
df %>%
  mutate(ACT_MIN = as.numeric(str_sub(df$`ACT Middle 50%`,1,2)))%>%
  mutate(ACT_MAX = as.numeric(str_sub(df$`ACT Middle 50%`,4,5)))%>%
  mutate(SAT_MIN = as.numeric(str_sub(df$`SAT Middle 50%`,1,4)))%>%
  mutate(SAT_MAX = as.numeric(str_sub(df$`SAT Middle 50%`,6,9)))
```


```{r}
#Convert character data to numerical data
df_plot = df
df_plot$`Undergraduate Population` = as.numeric(str_replace_all(df_plot$`Undergraduate Population`, ",", ""))
df_plot$`Application Fee` = as.numeric(gsub("\\$", "", df_plot$`Application Fee`))
df_plot$`Acceptance Rate` = as.numeric(str_remove_all(df_plot$`Acceptance Rate`, "%"))
df_plot$`Acceptance Rate` = df_plot$`Acceptance Rate`/100 #This line can just run once!!

df_plot$`Annual Tuition` = as.numeric(gsub("\\$", "", str_remove_all(df_plot$`Annual Tuition`, ",")))
df_plot$`Student:Faculty Ratio` = as.numeric(str_remove_all(df_plot$`Student:Faculty Ratio`, ":1"))
str(df_plot)

```
