---
title: "school_ggplot"
author: "Augustus Ge"
date: "November 26, 2018"
output: html_document
---
```{r}
# Data prepping
# Grouping schools in ranking by 5s
ACT_MIN_by_5s <- vector()
ACT_MAX_by_5s <- vector()
SAT_MIN_by_5s <- vector()
SAT_MAX_by_5s <- vector()
for(i in 1:20){
  # ACT_MIN_by_5s
  ACT_MIN_by_5s[i] <- mean(c(df$ACT_MIN[5*(i-1) + 1], df$ACT_MIN[5*(i-1) + 2], df$ACT_MIN[5*(i-1) + 3], df$ACT_MIN[5*(i-1) + 4], df$ACT_MIN[5*(i-1) + 5]), na.rm = TRUE)
  # ACT_MAX_by_5s
  ACT_MAX_by_5s[i] <- mean(c(df$ACT_MAX[5*(i-1) + 1], df$ACT_MAX[5*(i-1) + 2], df$ACT_MAX[5*(i-1) + 3], df$ACT_MAX[5*(i-1) + 4], df$ACT_MAX[5*(i-1) + 5]), na.rm = TRUE)
  # SAT_MIN_by_5s
  SAT_MIN_by_5s[i] <- mean(c(df$SAT_MIN[5*(i-1) + 1], df$SAT_MIN[5*(i-1) + 2], df$SAT_MIN[5*(i-1) + 3], df$SAT_MIN[5*(i-1) + 4], df$SAT_MIN[5*(i-1) + 5]), na.rm = TRUE)
  # SAT_MAX_by_5s
  SAT_MAX_by_5s[i] <- mean(c(df$SAT_MAX[5*(i-1) + 1], df$SAT_MAX[5*(i-1) + 2], df$SAT_MAX[5*(i-1) + 3], df$SAT_MAX[5*(i-1) + 4], df$SAT_MAX[5*(i-1) + 5]), na.rm = TRUE)
}

# Create this new data frame of standardized test scores corresponding to school rank by 5s
exam_df_by_5s <- as.data.frame(matrix(nrow = 20, ncol = 5))
exam_df_by_5s[,1] <- c("1-5", "6-10", "11-15", "16-20", "21-25", "26-30", "31-35", "36-40", "41-45", "46-50", "51-55", "56-60", "61-65", "66-70", "71-75", "76-80", "81-85", "86-90", "91-95", "96-100")
exam_df_by_5s[,2] <- ACT_MIN_by_5s
exam_df_by_5s[,3] <- ACT_MAX_by_5s
exam_df_by_5s[,4] <- SAT_MIN_by_5s
exam_df_by_5s[,5] <- SAT_MAX_by_5s
colnames(exam_df_by_5s) <- c("School_Rank", "Min_ACT", "Max_ACT", "Min_SAT", "Max_SAT")

# Factor so as to order the x axis 
exam_df_by_5s$School_Rank <- factor(exam_df_by_5s$School_Rank, levels = exam_df_by_5s[,1])


```



```{r}
# Visualizing standardized testing scores by ventile ranking (20 total groups)

ACT_plot <- ggplot(data = exam_df_by_5s, aes(x = School_Rank), width = .1) +
  geom_errorbar(aes(ymin = exam_df_by_5s$Min_ACT, ymax = exam_df_by_5s$Max_ACT), color = "blue", size = 1.2, alpha = .7) + 
  labs(title = "ACT Middle 50% Scoring Range", x = "Top 100 Schools Ventiles", y = "ACT Score") +
  theme_economist() +
  # Rename by ventile rank
  scale_x_discrete(labels = c(1:20))
  
SAT_plot <- ggplot(data = exam_df_by_5s, aes(x = School_Rank)) +
  geom_errorbar(aes(ymin = exam_df_by_5s$Min_SAT, ymax = exam_df_by_5s$Max_SAT), color = "blue", size = 1.2, alpha = .7) +
  labs(title = "SAT Middle 50% Scoring Range", x = "Top 100 Schools Ventiles", y = "SAT Score") +
  theme_economist() +
  # Rename by ventile rank
  scale_x_discrete(labels = c(1:20))

ACT_plot
SAT_plot
  
```
